ViewModels/Order/DetailViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NowBuySell.Web.ViewModels.Order
{
	public class DetailViewModel
	{
		public long? ID { get; set; }
		public long VendorID { get; set; }
		public long CarID { get; set; }
		public long? CarVaraiationID { get; set; }
		public int Quantity { get; set; }

		public string CustomNote { get; set; }

		public List<AttributesViewModel> Attributes { get; set; }
	}
}

ViewModels/Tags/CarTagsViewModel.cs
using NowBuySell.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NowBuySell.Web.ViewModels.Tags
{
    public class CarTagsViewModel
    {
        public long ID { get; set; }
        public bool IsPublished { get; set; }
        public bool IsRecommended { get; set; }
        public bool IsTaxInclusive { get; set; }
        public bool IsFeatured { get; set; }

        public List<CarTag> tag { get; set; }
    }
}

Areas/Admin/Controllers/TagsController.cs
using NowBuySell.Data;
using NowBuySell.Service;
using NowBuySell.Web.AuthorizationProvider;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using OfficeOpenXml;

namespace NowBuySell.Web.Areas.Admin.Controllers
{
    [AuthorizeAdmin]
    public class TagsController : Controller
    {
        string ErrorMessage = string.Empty;
        string SuccessMessage = string.Empty;
        private readonly ITagService _tagsService;

        public TagsController(ITagService tagsService)
        {
            this._tagsService = tagsService;

        }
      
        // GET: Admin/Tags
        public ActionResult Index()
        {
            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            ViewBag.ExcelUploadErrorMessage = TempData["ExcelUploadErrorMessage"];
            return View();
        }
        public ActionResult List()
        {
            var tags = _tagsService.GetTags();
            return PartialView(tags);

        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Tag data)
        {
            string message = string.Empty;
            if (ModelState.IsValid)
            {
                if (_tagsService.CreateTag( ref data, ref message))
                {
                    return Json(new
                    {
                        success = true,
                        url = "/Admin/Tags/Index",
                        message = message,
                        data = new
                        {
                            Date = data.CreatedOn.Value.ToString("dd MMM yyyy, h:mm tt"),
                            Name = data.Name,
                            IsActive = data.IsActive.HasValue ? data.IsActive.Value.ToString() : bool.FalseString,
                            ID = data.ID
                        }
                    });
                }
            }
            else
            {
                message = "Please fill the form properly ...";
            }

            return Json(new { success = false, message = message });
        }

        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = _tagsService.GetTag((long)id);
            if (tag == null)
            {
                return HttpNotFound();
            }

            TempData["tagID"] = id;
            return View(tag);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tag tag)
        {
            string message = string.Empty;
            if (ModelState.IsValid)
            {
                long Id;
                if (TempData["tagID"] != null && Int64.TryParse(TempData["tagID"].ToString(), out Id) && tag.ID == Id)
                {
                    if (_tagsService.UpdateTag(ref tag, ref message))
                    {
                        return Json(new
                        {
                            success = true,
                            url = "/Admin/Brands/Index",
                            message = "Tag updated successfully ...",
                            data = new
                            {
                                Date = tag.CreatedOn.Value.ToString("dd MMM yyyy, h:mm tt"),
                                Name = tag.Name,
                                IsActive = tag.IsActive.HasValue ? tag.IsActive.Value.ToString() : bool.FalseString,
                                ID = tag.ID
                            }
                        });
                    }

                }
                else
                {
                    message = "Oops! Something went wrong. Please try later.";
                }
            }
            else
            {
                message = "Please fill the form properly ...";
            }
            return Json(new { success = false, message = message });
        }
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = _tagsService.GetTag((Int16)id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            TempData["tagID"] = id;
            return View(tag);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            string message = string.Empty;
            if (_tagsService.DeleteTag((Int16)id, ref message))
            {
                return Json(new { success = true, message = message }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, message = message }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Activate(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tag = _tagsService.GetTag((long)id);
            if (tag == null)
            {
                return HttpNotFound();
            }

            if (!(bool)tag.IsActive)
                tag.IsActive = true;
            else
            {
                tag.IsActive = false;
            }
            string message = string.Empty;
            if (_tagsService.UpdateTag(ref tag, ref message))
            {
                SuccessMessage = "Tag " + ((bool)tag.IsActive ? "activated" : "deactivated") + "  successfully ...";
                return Json(new
                {
                    success = true,
                    message = SuccessMessage,
                    data = new
                    {
                        Date = tag.CreatedOn.Value.ToString("dd MMM yyyy, h:mm tt"),
                        Name = tag.Name,
                        IsActive = tag.IsActive.HasValue ? tag.IsActive.Value.ToString() : bool.FalseString,
                        ID = tag.ID
                    }
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                ErrorMessage = "Oops! Something went wrong. Please try later.";
            }

            return Json(new { success = false, message = ErrorMessage }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = _tagsService.GetTag((Int16)id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TagsReport()
        {
            var getAllTags = _tagsService.GetTags().ToList();
            if (getAllTags.Count() > 0)
            {
                using (ExcelPackage excel = new ExcelPackage())
                {
                    excel.Workbook.Worksheets.Add("TagsReport");

                    var headerRow = new List<string[]>()
                    {
                    new string[] {
                        "Creation Date"
                        ,"Name"
                        ,"Status"
                        }
                    };

                    // Determine the header range (e.g. A1:D1)
                    string headerRange = "A1:" + char.ConvertFromUtf32(headerRow[0].Length + 64) + "1";

                    // Target a worksheet
                    var worksheet = excel.Workbook.Worksheets["TagsReport"];

                    // Popular header row data
                    worksheet.Cells[headerRange].LoadFromArrays(headerRow);

                    var cellData = new List<object[]>();

                    foreach (var i in getAllTags)
                    {
                        cellData.Add(new object[] {
                        i.CreatedOn.HasValue ? i.CreatedOn.Value.ToString("dd MMM yyyy, h:mm tt") : "-"
                        ,!string.IsNullOrEmpty(i.Name) ? i.Name : "-"
                        ,i.IsActive == true ? "Active" : "InActive"
                        });
                    }

                    worksheet.Cells[2, 1].LoadFromArrays(cellData);

                    return File(excel.GetAsByteArray(), "application/msexcel", "Tags Report.xlsx");
                }
            }
            return RedirectToAction("Index");
        }

    }
}

Areas/Admin/Views/Tags/Create.cshtml
@model NowBuySell.Data.Tag

@{
    ViewBag.Title = "Create";
    Layout = null;
}
<div class="modal-header">
    <h5 class="modal-title">Create</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i aria-hidden="true" class="ki ki-close"></i>
    </button>
</div>
<div class="modal-body">

    @using (Html.BeginForm("Create", "Tags", new { area = "Admin" }, FormMethod.Post, new { id = "Userform", @class = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="alert alert-danger text-center" id="divMessage" style="display:none"></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, "Tag Name", htmlAttributes: new { @class = "control-label" })
                    <div class="input-group mb-2">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter tag name here ...", required = "required" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        <div class="input-group-append"><span class="input-group-text"><i class="fa fa-tags"></i></span></div>
                    </div>
                </div>
            </div>
            @*<div class="col-md-6 col-sm-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.NameAr, " Tag Name (Ar)", htmlAttributes: new { @class = "control-label" })
                    <div class="input-group mb-2">
                        @Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter tag name (ar) here ...", required = "required", dir = "rtl" } })
                        @Html.ValidationMessageFor(model => model.NameAr, "", new { @class = "text-danger" })
                        <div class="input-group-append"><span class="input-group-text"><i class="fa fa-tags"></i></span></div>
                    </div>
                </div>
            </div>*@
        </div>
    }
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-info" form="Userform">Submit</button>
</div>

Areas/Admin/Views/Tags/Details.cshtml
@model NowBuySell.Data.Tag

@{
    ViewBag.Title = "Details";
    Layout = null;
}


<div class="modal-header">
    <h5 class="modal-title">Details</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i aria-hidden="true" class="ki ki-close"></i>
    </button>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="float-right mb-3">
                <i class="fa fa-calendar"></i>
                <b>@Html.Label("Creation Date:", htmlAttributes: new { @class = "control-label" })</b>
                @if (Model.CreatedOn.HasValue)
                {
                    var date = Model.CreatedOn.Value.ToString("dd MMM yyyy, h:mm tt");
                    <label class="control-label" readonly="readonly">@date</label>
                }
                else
                {
                    <label class="control-label" readonly="readonly"> - </label>
                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="form-group">
                <label class="control-label">Tag Name</label>
                <div class="input-group mb-3">
                    <label class="form-control" readonly="readonly">@Model.Name</label>
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fa fa-tags"></i></span>
                    </div>
                </div>
            </div>
        </div>
        @*<div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label class="control-label">Tag Name (Ar)</label>
                <div class="input-group mb-3">
                    <label class="form-control float-right" readonly="readonly">@Model.NameAr</label>
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fa fa-tags"></i></span>
                    </div>
                </div>
            </div>
        </div>*@
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

Areas/Admin/Views/Tags/Edit.cshtml
@model NowBuySell.Data.Tag
@{
    ViewBag.Title = "Edit";
    Layout = null;
}

<div class="modal-header">
    <h5 class="modal-title">Update</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i aria-hidden="true" class="ki ki-close"></i>
    </button>
</div>
<div class="modal-body">

    @using (Html.BeginForm("Edit", "Tags", new { area = "Admin" }, FormMethod.Post, new { id = "frm-edit", @class = "form" }))
    {
        @Html.AntiForgeryToken()
        <div class="alert alert-danger text-center" id="divMessage" style="display:none"></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, "Tag Name", htmlAttributes: new { @class = "control-label" })
                    <div class="input-group mb-2">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter tag name here ...", required = "required" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        <div class="input-group-append"><span class="input-group-text"><i class="fa fa-tags"></i></span></div>
                    </div>
                </div>
            </div>
            @*<div class="col-md-6 col-sm-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.NameAr, "Tag Name (Ar)", htmlAttributes: new { @class = "control-label" })
                    <div class="input-group mb-2">
                        @Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter tag name (ar) here ...", required = "required", dir = "rtl" } })
                        @Html.ValidationMessageFor(model => model.NameAr, "", new { @class = "text-danger" })
                        <div class="input-group-append"><span class="input-group-text"><i class="fa fa-tags"></i></span></div>
                    </div>
                </div>
            </div>*@
        </div>
    }
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-info" form="frm-edit">Save Changes</button>
</div>

Areas/Admin/Views/Tags/Index.cshtml
@model NowBuySell.Data.Tag

@{
    ViewBag.Title = "Motor Tags";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<!--begin::Page Vendors Styles(used by this page)-->
<link href="~/assets/Admin/plugins/custom/datatables/datatables.bundle.css" rel="stylesheet" type="text/css" />
<!--end::Page Vendors Styles-->
<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-12 subheader-transparent" id="kt_subheader">
        <div class="container d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Heading-->
                <div class="d-flex flex-column">

                    <!--begin::Breadcrumb-->
                    <div class="d-flex align-items-center font-weight-bold my-2">
                        <!--begin::Item-->
                        <a href="/Admin/Dashboard/Index" class="opacity-75 hover-opacity-100">
                            <i class="flaticon2-shelter text-white icon-1x"></i>
                        </a>
                        <!--end::Item-->
                        <!--begin::Item-->
                        <a href="/Admin/Dashboard/Index" class="text-white text-hover-white opacity-75 hover-opacity-100">&nbsp;&nbsp;Dashboard</a>
                        <!--end::Item-->
                        <!--begin::Item-->
                        <span class="label label-dot label-sm bg-white opacity-75 mx-3"></span>
                        <a href="javascript:;" class="text-white text-hover-white opacity-75 hover-opacity-100">Tags</a>
                        <!--end::Item-->
                    </div>
                    <!--end::Breadcrumb-->
                </div>
                <!--end::Heading-->
            </div>
            <!--end::Info-->
        </div>
    </div>
    <!--end::Subheader-->
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Dashboard-->
            @{ Html.RenderAction("List", "Tags", new { area = "Admin" }); }
            <!--end::Dashboard-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
</div>
<!--end::Content-->
@*<div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">
        <!-- begin:: Subheader -->
        <div class="kt-subheader   kt-grid__item" id="kt_subheader">
            <div class="kt-container  kt-container--fluid ">
                <div class="kt-subheader__main">
                    <h3 class="kt-subheader__title">
                        Dashboard
                    </h3>
                    <span class="kt-subheader__separator kt-hidden"></span>
                    <div class="kt-subheader__breadcrumbs">
                        <a href="/Home/RealEstateIndex" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                        <span class="kt-subheader__breadcrumbs-separator"></span>
                        <a class="kt-subheader__breadcrumbs-link">
                            Tenants
                        </a>
                        <!-- <span class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--active">Active link</span> -->
                    </div>
                </div>

            </div>
        </div>

        <!-- end:: Subheader -->
        <!-- begin:: Content -->
        <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">

            <!--Begin::Row-->

            <link href="@Url.ContentVersioned("~/assets/Admin/plugins/custom/datatables/datatables.bundle.css")" rel="stylesheet" type="text/css" />
            <script src="@Url.ContentVersioned("~/assets/Admin/plugins/custom/datatables/datatables.bundle.js")" defer type="text/javascript"></script>

            <!--begin::Page Scripts(used by this page) -->
            <script src="@Url.ContentVersioned("~/assets/scripts/ModalPopup.js")"></script>
            <!--End::Row-->

            @{ Html.RenderAction("List", "Tenant"); }
        </div>

        <!-- end:: Content -->
    </div>*@

<div id="myModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content" style="min-height:100px">
            <div id='myModalContent'>
                <div class="row justify-content-center">
                    <div class="col-16">
                        <div class="kt-spinner kt-spinner--lg kt-spinner--dark kt-spinner-modal"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<!--end::Row-->
@section IndexScript {
    @if (ViewBag.SuccessMessage != null)
    {
        <script>
        toastr.success('@ViewBag.SuccessMessage');
        </script>
    }
    else if (ViewBag.ErrorMessage != null)
    {
        <script>
        toastr.error('@ViewBag.ErrorMessage');
        </script>
    }

    @if (ViewBag.ExcelUploadErrorMessage != null)
    {
        <script>
		swal.fire({
			title: '@ViewBag.ErrorMessage',
			html: '@Html.Raw(ViewBag.ExcelUploadErrorMessage)',
			type: 'error',
		});
        </script>
    }

    <!--begin::Page Vendors(used by this page)-->
    @*<script src="~/assets/Admin/plugins/custom/datatables/datatables.bundle.js"></script>*@
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap4.min.js"></script>
    <!--end::Page Vendors-->
    <!--begin::Page Scripts(used by this page)-->

    <script src="@Url.ContentVersioned("~/Assets/Admin/js/admin/tags/list.js")"></script>
    <!--end::Page Scripts-->
    <script src="~/Assets/Admin/js/general/ModalPopup.js"></script>
    <!--end::Page Scripts-->
}

Areas/Admin/Views/Tags/List.cshtml
@model IEnumerable<NowBuySell.Data.Tag>


@{
    ViewBag.Title = "List";
    Layout = null;
}
<style>
    #kt_datatable1 tbody tr td:last-child {
        white-space: nowrap;
    }
</style>
<!--begin::Row-->
<div class="row">
    <div class="col-xl-12">
        <!--begin::Card-->
        <div class="card card-custom gutter-b">
            <div class="card-header flex-wrap border-0 pt-6 pb-0">
                <div class="card-title">
                    <h3 class="card-label">
                        Tags
                        <span class="d-block text-muted pt-2 font-size-sm">Manage Tags Here...</span>
                    </h3>
                </div>
                <div class="card-toolbar">
                    <!--begin::Dropdown-->
                    <div class="dropdown dropdown-inline mr-2">
                        @using (Html.BeginForm("TagsReport", "Tags", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()

                            <button type="submit" class="btn btn-dark btn-sm" @(Model.Count() > 0 ? "": "disabled")>
                                <i class="far fa-file-excel"></i>
                                Export Excel
                            </button>
                        }
                    </div>

                    @*<div class="dropdown dropdown-inline mr-2">
                            <a href="~/Assets/AppFiles/Documents/CSVSample/BulkCountry.xlsx" download type="button" class="btn btn-dark btn-sm">
                                <i class="fa fa-download"></i>
                                Sample CSV
                            </a>
                        </div>

                        <div class="dropdown dropdown-inline mr-2">
                            <button type="button" class="btn btn-dark btn-sm" onclick="OpenModelPopup(this, '/Admin/Country/BulkUpload')" data="/Admin/Country/BulkUpload">
                                <i class="fa fa-plus"></i>
                                Bulk Upload
                            </button>
                        </div>*@
                    <!--end::Dropdown-->
                    <!--begin::Button-->
                    <a href="javascript:;" class="btn btn-info font-weight-bolder" onclick="OpenModelPopup(this, '/Admin/Tags/Create')">
                        <span class="svg-icon svg-icon-md">
                            <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <rect x="0" y="0" width="24" height="24" />
                                    <circle fill="#000000" cx="9" cy="15" r="6" />
                                    <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                                </g>
                            </svg>
                            <!--end::Svg Icon-->
                        </span>New Record
                    </a>
                    <!--end::Button-->
                </div>
            </div>
            <div class="card-body">
                @Html.AntiForgeryToken()
                <!--begin: Datatable-->
                <table class="table table-separate table-head-custom table-checkable" id="kt_datatable1">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody style="display:none">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@(item.CreatedOn.HasValue ? item.CreatedOn.Value.ToString("dd MMM yyyy, h:mm tt") : "-")	</td>
                                <td>@item.Name</td>

                                <td>@(item.IsActive.HasValue ? item.IsActive.Value : false)</td>
                                <td nowrap="nowrap">@item.IsActive,@item.ID</td>
                            </tr>
                        }
                    </tbody>
                </table>
                <!--end: Datatable-->
            </div>
        </div>
        <!--end::Card-->
    </div>
</div>
<!--end::Row-->