Areas/Admin/Controllers/ContentManagmentController.cs
using NowBuySell.Data;
using NowBuySell.Service;
using NowBuySell.Web.Areas.Admin.ViewModels.Banners;
using NowBuySell.Web.AuthorizationProvider;
using NowBuySell.Web.Helpers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NowBuySell.Web.Areas.Admin.Controllers
{
	[AuthorizeAdmin]
	public class ContentManagmentController : Controller
    {
        private readonly IBannerImagesService _bannnerImageService;
		private readonly IPromoBannerService _promobannnerImageService;

		public ContentManagmentController(IBannerImagesService bannnerImageService, IPromoBannerService promobannnerImageService)
        {
            this._bannnerImageService = bannnerImageService;
            _promobannnerImageService = promobannnerImageService;
        }
        public ActionResult Manage()
        {
			ViewBag.SuccessMessage = TempData["SuccessMessage"];
			ViewBag.ErrorMessage = TempData["ErrorMessage"];
			BannersViewModel objBannersViewModel = new BannersViewModel()
            {
                WebsiteBanners = _bannnerImageService.GetBanners().ToList(),
				PromoBannerWeb = _promobannnerImageService.GetBanners().ToList(),
			};

            return View(objBannersViewModel);
        }
        [HttpPost]
		public ActionResult Manage(HttpPostedFileBase file, string Url, string Lang, string ContentType, string MVType, string Description, string DescriptionAr)
		{
			var banner = _bannnerImageService.GetBannersByType("WebsiteHeader").ToList();
            if (banner.Count == 0)
            {
				string message = string.Empty;
				if (file != null && file.ContentLength > 0)

					try
					{
						if (ContentType == "Image")
						{

							string path = Path.Combine(Server.MapPath("~/Assets/AppFiles/Banners/"));
							string newfilename = "web-banner-header" + Guid.NewGuid().ToString() + ".jpg";
							// file.FileName = newfilename;

							Path.GetFileName(file.FileName);
							file.SaveAs(path + newfilename);
							BannerImage objBannerImage = new BannerImage();
							objBannerImage.ImagePath = "/Assets/AppFiles/Banners/" + newfilename;
							objBannerImage.Url = Url;
							objBannerImage.Lang = Lang;
							objBannerImage.BannerType = MVType;
							objBannerImage.Module = "Website";
							objBannerImage.Description = Description;
							objBannerImage.DescriptionAr = DescriptionAr;
							objBannerImage.ContentType = ContentType;

							if (_bannnerImageService.CreateBanner(objBannerImage, ref message))
							{

							}
							TempData["SuccessMessage"] = "File uploaded successfully";
						}
						else
						{

							BannerImage objBannerImage = new BannerImage();
							string newfilename = "web-banner-header" + Guid.NewGuid().ToString() + ".jpg";
							string absolutePath = Server.MapPath("~");
							string relativePath = string.Format("/Assets/AppFiles/Banners/", newfilename);
							objBannerImage.ImagePath = Uploader.UploadVideo(Request.Files, absolutePath, relativePath, "Video", ref message, "file");

							//objBannerImage.ImagePath = "/Assets/AppFiles/Banners/" + newfilename;
							objBannerImage.Url = Url;
							objBannerImage.Lang = Lang;
							objBannerImage.BannerType = MVType;
							objBannerImage.Module = "Website";
							objBannerImage.Description = Description;
							objBannerImage.DescriptionAr = DescriptionAr;
							objBannerImage.ContentType = ContentType;

							if (_bannnerImageService.CreateBanner(objBannerImage, ref message))
							{

							}
							TempData["SuccessMessage"]= "File uploaded successfully";
						}

					}
					catch (Exception ex)
					{
						TempData["ErrorMessage"] = "ERROR:" + ex.Message.ToString();
					}
				else
				{
					TempData["ErrorMessage"] = "You have not specified a file.";
				}

			}
            else
            {
				TempData["ErrorMessage"] = "Cannot add more than One header image or video.";
			}
			
			return RedirectToAction("Manage");
		}


        [HttpPost]
        public ActionResult MotorSideBanner(HttpPostedFileBase file, string Url, string Lang, string ContentType, string MVType, string Description, string DescriptionAr)
        {
            var banner = _bannnerImageService.GetBannersByTypeAndLang("MotorSideBanner",Lang).ToList();
            if (banner.Count == 0)
            {
                string message = string.Empty;
                if (file != null && file.ContentLength > 0)

                    try
                    {
                            string path = Path.Combine(Server.MapPath("~/Assets/AppFiles/Banners/"));
                            string newfilename = "motor-side-banner" + Guid.NewGuid().ToString() + ".jpg";
                            // file.FileName = newfilename;

                            Path.GetFileName(file.FileName);
                            file.SaveAs(path + newfilename);
                            BannerImage objBannerImage = new BannerImage();
                            objBannerImage.ImagePath = "/Assets/AppFiles/Banners/" + newfilename;
                            objBannerImage.Url = Url;
                            objBannerImage.Lang = Lang;
                            objBannerImage.BannerType = MVType;
                            objBannerImage.Module = "Website";
                            objBannerImage.Description = Description;
                            objBannerImage.DescriptionAr = DescriptionAr;
                            objBannerImage.ContentType = ContentType;

                            if (_bannnerImageService.CreateBanner(objBannerImage, ref message))
                            {

                            }
						TempData["SuccessMessage"] = "File uploaded successfully";
                   

                    }
                    catch (Exception ex)
                    {
						TempData["ErrorMessage"] = "ERROR:" + ex.Message.ToString();
                    }
                else
                {
					TempData["ErrorMessage"] = "You have not specified a file.";
                }

            }
            else
            {
				TempData["ErrorMessage"] = "Cannot add more than One Side Banner image .";
            }

            return RedirectToAction("Manage");
        }
        [HttpPost]
        public ActionResult PropertySideBanner(HttpPostedFileBase file, string Url, string Lang, string ContentType, string MVType, string Description, string DescriptionAr)
        {
            var banner = _bannnerImageService.GetBannersByTypeAndLang("PropertySideBanner",Lang).ToList();
            if (banner.Count == 0)
            {
                string message = string.Empty;
                if (file != null && file.ContentLength > 0)

                    try
                    {
                        string path = Path.Combine(Server.MapPath("~/Assets/AppFiles/Banners/"));
                        string newfilename = "property-side-banner" + Guid.NewGuid().ToString() + ".jpg";
                        // file.FileName = newfilename;

                        Path.GetFileName(file.FileName);
                        file.SaveAs(path + newfilename);
                        BannerImage objBannerImage = new BannerImage();
                        objBannerImage.ImagePath = "/Assets/AppFiles/Banners/" + newfilename;
                        objBannerImage.Url = Url;
                        objBannerImage.Lang = Lang;
                        objBannerImage.BannerType = MVType;
                        objBannerImage.Module = "Website";
                        objBannerImage.Description = Description;
                        objBannerImage.DescriptionAr = DescriptionAr;
                        objBannerImage.ContentType = ContentType;

                        if (_bannnerImageService.CreateBanner(objBannerImage, ref message))
                        {

                        }
						TempData["SuccessMessage"] = "File uploaded successfully";


                    }
                    catch (Exception ex)
                    {
						TempData["ErrorMessage"] = "ERROR:" + ex.Message.ToString();
                    }
                else
                {
					TempData["ErrorMessage"] = "You have not specified a file.";
                }

            }
            else
            {
				TempData["ErrorMessage"] = "Cannot add more than One Side Banner image .";
            }

            return RedirectToAction("Manage");
        }
		[HttpPost]
		public ActionResult MainBanner(HttpPostedFileBase file, string Url, string ContentType, string Lang, string Type, string MVType, string Description, string DescriptionAr)
		{
			string message = string.Empty;
			if (file != null && file.ContentLength > 0)
				try
				{
					string path = Path.Combine(Server.MapPath("~/Assets/AppFiles/Banners/"));
					string newfilename = "web-banner-" + Guid.NewGuid().ToString() + ".jpg";
					// file.FileName = newfilename;

					Path.GetFileName(file.FileName);
					file.SaveAs(path + newfilename);
					BannerImage objBannerImage = new BannerImage();
					objBannerImage.ImagePath = "/Assets/AppFiles/Banners/" + newfilename;
					objBannerImage.Url = Url;
					objBannerImage.Lang = Lang;
					objBannerImage.BannerType = MVType;
					objBannerImage.Module = MVType == "Mobile" ? null : Type;
					objBannerImage.Description = Description;
					objBannerImage.DescriptionAr = DescriptionAr;
					objBannerImage.ContentType = ContentType;

					if (_bannnerImageService.CreateBanner(objBannerImage, ref message))
					{
						if(MVType != "Mobile")
                        {
							objBannerImage.Lang = "ar";
							_bannnerImageService.CreateBanner(objBannerImage, ref message);
						}
						
					}
					TempData["SuccessMessage"] = "File uploaded successfully";
				}
				catch (Exception ex)
				{
					TempData["ErrorMessage"] = "ERROR:" + ex.Message.ToString();
				}
			else
			{
				TempData["ErrorMessage"] = "You have not specified a file.";
			}
			return RedirectToAction("Manage");
		}
		[HttpPost]

Areas/Admin/Views/ContentManagment/Edit.cshtml
@model NowBuySell.Data.BannerImage
@{
    ViewBag.Title = "NoyBuySell | Edit";
    Layout = null;
}

<div class="modal-header">
    <h5 class="modal-title">Banner</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i aria-hidden="true" class="ki ki-close"></i>
    </button>
</div>
<div class="modal-body">
    @using (Html.BeginForm("Edit", "ContentManagment", new { area = "Admin" }, FormMethod.Post, new { id = "HeaderImageform" }))
    {
        @Html.HiddenFor(Model => Model.ID)
        @Html.AntiForgeryToken()
        <input name="MVType" value="@Model.BannerType" hidden />
        <div class="row">
            <div class="col-md-12" style="margin-top:20px">
                @{
                    if (Model.ContentType == "Image")
                    {
                        <div class="bgi-no-repeat bgi-size-cover rounded min-h-200px shadow-sm" style="background-position: 50% 50%;background-image: url(@Model.ImagePath)"></div>

                    }
                    else
                    {
                        <video id="VideoTag" width="100%" height="auto" controls="controls" preload="metadata" style="width:100%;height:auto">
                            <source id="videoSource" src="@Model.ImagePath#t=0.5" type="video/mp4">
                        </video>
                    }
                }
                @*<div class="form-group mt-3">
                    <label class="control-label">Language</label>
                    <div class="input-group">
                        <select name="Lang" id="Lang" class="form-control" required>
                            <option value="en">English</option>
                            <option value="ar">Arabic</option>
                        </select>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-globe-asia"></i>
                            </span>
                        </div>
                    </div>
                </div>*@



                <div class="form-group mt-3">
                    <label class="control-label">Url (Where to navigate on click)</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="Url" id="Url" placeholder="Redirect to" required value="@Model.Url" />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="flaticon2-open-text-book"></i>
                            </span>
                        </div>
                    </div>
                </div>

                @*<div class="form-group mt-3">
                    <div class="form-group">
                        <label class="control-label">Description</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="Description" id="Description" placeholder="Description" value="@Model.Description" />
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="flaticon2-open-text-book"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group mt-3">
                    <div class="form-group">
                        <label class="control-label">Description Ar</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="DescriptionAr" id="DescriptionAr" placeholder="وصف" dir="rtl" value="@Model.DescriptionAr" />
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="flaticon2-open-text-book"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>*@


            </div>
        </div>
    }
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-info" form="HeaderImageform">Submit</button>
</div>

<script>

    $(document).ready(function () {

        var bannerType = '@Model.BannerType';

        if (bannerType.toLowerCase() == 'website') {
            var module = '@Model.Module';
            $("#Type").val(module);
            $("#Type option[value=" + module + "]").attr('selected', 'selected');
        }


		$('#HeaderImageform #Lang').val('@Model.Lang')

        $('#HeaderImageform').submit(function () {
            
			$.ajax({
				url: this.action,
				type: this.method,
				data: jQuery(this).serialize(),
				success: function (response) {
					if (response.success) {
                        @*$('.website-banner[data=@Model.ID] .btn-lang').text(response.data.lang);*@

                        $('.website-banner[data=@Model.ID] .btn-module').text(response.data.module);

						toastr.success(response.message);
						$('#myModal').modal('hide');
					} else {
						toastr.error(response.message);
						$('#HeaderImageform').closest('.modal').find('button[type=submit]').removeClass('spinner spinner-sm spinner-left').attr('disabled', false);
					}
				}
			});
			return false;
		});
	});

</script>